/*
 * YAJHFC - Yet another Java Hylafax client
 * Copyright (C) 2005-2010 Jonas Wolz
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package yajhfc.options;

import static yajhfc.Utils._;
import info.clearthought.layout.TableLayout;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Properties;

import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import yajhfc.FaxOptions;
import yajhfc.Utils;
import yajhfc.util.ExcDialogAbstractAction;
import yajhfc.util.ExceptionDialog;
import yajhfc.util.SafeJFileChooser;

/**
 * @author jonas
 *
 */
public class AdminSettingsPage extends JPanel implements OptionsPage {
    protected final OptionsWin parentWin;
    private static final int border = 6;
    
    JCheckBox checkUseWin32ShutdownManager, checkAdjustMenusForMacOSX, checkUseJDK16PSBugfix;
    JCheckBox checkRegardingAsUsrKey, checkAllowChangeFilter;
    JFileChooser fileChooser;
    
    Action actImport, actExport;
    
    public AdminSettingsPage(OptionsWin parentWin) {
        super(false);
        this.parentWin = parentWin;
        initialize();
    }
    
    private void initialize() {
        double[][] dLay = {
                {border, 0.75, border, TableLayout.FILL, border},
                {border, TableLayout.PREFERRED, border*2, TableLayout.FILL, border}
        };
        setLayout(new TableLayout(dLay));
        
        JLabel descriptionLabel = new JLabel("<html>" + _("This page allows you to import/export settings and to set miscellaneous advanced settings (change them only if you know what you are doing; you may need to restart YajHFC for them to take effect).") + "</html>");
        
        add(descriptionLabel, "1,1,3,1");
        add(createSettingsPanel(), "1,3");
        add(createImportExportPanel(), "3,3");
    }
    
    private JPanel createSettingsPanel() {
        JPanel settingsPanel = new JPanel(null, false);
        settingsPanel.setLayout(new BoxLayout(settingsPanel, BoxLayout.Y_AXIS));
        settingsPanel.setBorder(BorderFactory.createTitledBorder(_("Advanced settings") + ":"));
        
        Dimension spacer = new Dimension(border, border);
        checkAllowChangeFilter = new JCheckBox(_("Allow the user to change the fax job filter (View menu)"));
        checkRegardingAsUsrKey = new JCheckBox(_("Use the fax's subject as HylaFAX USRKEY property"));
        checkUseJDK16PSBugfix = new JCheckBox(_("Repair PostScript generated by JDK 1.6 PrintService classes"));
        checkUseWin32ShutdownManager = new JCheckBox(_("Use ShutdownHook bug fix on Win32"));
        checkAdjustMenusForMacOSX = new JCheckBox(_("Remove application menu entries from normal menu on Mac OS X"));
        
        settingsPanel.add(checkAllowChangeFilter);
        settingsPanel.add(Box.createRigidArea(spacer));
        settingsPanel.add(checkRegardingAsUsrKey);
        settingsPanel.add(Box.createRigidArea(spacer));
        settingsPanel.add(checkUseJDK16PSBugfix);
        settingsPanel.add(Box.createRigidArea(spacer));
        settingsPanel.add(checkUseWin32ShutdownManager);
        settingsPanel.add(Box.createRigidArea(spacer));
        settingsPanel.add(checkAdjustMenusForMacOSX);
        
        return settingsPanel;
    }
    
    JFileChooser getFileChooser() {
        if (fileChooser == null) {
            fileChooser = new SafeJFileChooser();
            fileChooser.setFileHidingEnabled(false);
        }
        return fileChooser;
    }
    
    private JPanel createImportExportPanel() {
        actImport = new ExcDialogAbstractAction(_("Import settings") + "...") {
            @Override
            protected void actualActionPerformed(ActionEvent e) {
                JFileChooser chooser = getFileChooser();
                chooser.setDialogTitle(_("Import settings"));
                if (chooser.showOpenDialog(AdminSettingsPage.this) == JFileChooser.APPROVE_OPTION) {
                    try {
                        Properties p = new Properties();
                        FileInputStream inStream = new FileInputStream(chooser.getSelectedFile());
                        p.load(inStream);
                        inStream.close();
                        
                        FaxOptions newOpts = new FaxOptions();
                        newOpts.loadFromProperties(p);
                        parentWin.loadSettings(newOpts);
                        
                        JOptionPane.showMessageDialog(AdminSettingsPage.this, _("Settings imported successfully."));
                    } catch (Exception ex) {
                        ExceptionDialog.showExceptionDialog(AdminSettingsPage.this, _("Error importing settings:"), ex);
                    }
                }  
            }
        };
        
        actExport = new ExcDialogAbstractAction(_("Export settings") + "...") {
            @Override
            protected void actualActionPerformed(ActionEvent e) {
                JFileChooser chooser = getFileChooser();
                chooser.setDialogTitle(_("Export settings"));
                if (chooser.showSaveDialog(AdminSettingsPage.this) == JFileChooser.APPROVE_OPTION) {
                    try {
                        Properties p = new Properties();
                        FaxOptions newOpts = new FaxOptions();
                        
                        // Copy existing settings over: 
                        parentWin.foToEdit.storeToProperties(p);
                        newOpts.loadFromProperties(p);
                        
                        if (parentWin.saveSettings(newOpts)) {
                            newOpts.storeToProperties(p);
                            
                            FileOutputStream out = new FileOutputStream(chooser.getSelectedFile());
                            p.store(out, Utils.AppShortName + " " + Utils.AppVersion + " configuration file; exported from the options dialog");
                            out.close();
                        }
                    } catch (Exception ex) {
                        ExceptionDialog.showExceptionDialog(AdminSettingsPage.this, _("Error exporting settings:"), ex);
                    }
                }  
            }
        };
        
        JPanel importExportPanel = new JPanel(null, false);
        importExportPanel.setLayout(new TableLayout(new double[][] {
                {border, TableLayout.FILL, border},
                {border, TableLayout.PREFERRED, border, TableLayout.PREFERRED, TableLayout.FILL}
        }));
        importExportPanel.setBorder(BorderFactory.createTitledBorder(_("Import/Export")));
        
        importExportPanel.add(new JButton(actImport), "1,1");
        importExportPanel.add(new JButton(actExport), "1,3");
        
        return importExportPanel;
    }
    
    /* (non-Javadoc)
     * @see yajhfc.options.OptionsPage#loadSettings(yajhfc.FaxOptions)
     */
    public void loadSettings(FaxOptions foEdit) {
        checkAdjustMenusForMacOSX.setSelected(foEdit.adjustMenusForMacOSX);
        checkAllowChangeFilter.setSelected(foEdit.allowChangeFilter);
        checkRegardingAsUsrKey.setSelected(foEdit.regardingAsUsrKey);
        checkUseJDK16PSBugfix.setSelected(foEdit.useJDK16PSBugfix);
        checkUseWin32ShutdownManager.setSelected(foEdit.useWin32ShutdownManager);
    }

    /* (non-Javadoc)
     * @see yajhfc.options.OptionsPage#saveSettings(yajhfc.FaxOptions)
     */
    public void saveSettings(FaxOptions foEdit) {
        foEdit.adjustMenusForMacOSX = checkAdjustMenusForMacOSX.isSelected();
        foEdit.allowChangeFilter = checkAllowChangeFilter.isSelected();
        foEdit.regardingAsUsrKey =  checkRegardingAsUsrKey.isSelected();
        foEdit.useJDK16PSBugfix = checkUseJDK16PSBugfix.isSelected();
        foEdit.useWin32ShutdownManager = checkUseWin32ShutdownManager.isSelected();
    }

    /* (non-Javadoc)
     * @see yajhfc.options.OptionsPage#validateSettings(yajhfc.options.OptionsWin)
     */
    public boolean validateSettings(OptionsWin optionsWin) {
        return true;
    }

}
